[{"authorTime":"2020-03-12 03:06:42","codes":[{"authorDate":"2020-03-12 03:06:42","commitOrder":1,"curCode":"    public static void assertParentRepairSuccess(AbstractCluster<?> cluster, int coordinator, String ks, String table)\n    {\n        QueryResult rs = queryParentRepairHistory(cluster, coordinator, ks, table);\n        validateExistingParentRepair(rs, row -> {\n            \r\n            Assert.assertNotNull(\"finished_at not found, the repair is not complete?\", row.getTimestamp(\"finished_at\"));\n\n            \r\n            Assert.assertNull(\"Exception found\", row.getString(\"exception_stacktrace\"));\n            Assert.assertNull(\"Exception found\", row.getString(\"exception_message\"));\n        });\n    }\n","date":"2020-03-13 00:37:39","endLine":125,"groupId":"4324","id":1,"instanceNumber":1,"isCurCommit":0,"methodName":"assertParentRepairSuccess","params":"(AbstractCluster<?>cluster@intcoordinator@Stringks@Stringtable)","path":"/mnt/clonedata/CloneManagementServer/ManagementServer/consistResult/result-cassandra-10-0.7/blobInfo/CC_OUT/blobs/7f/162e14654ec071beb43d3231c525143738bcc2.src","preCode":"    public static void assertParentRepairSuccess(AbstractCluster<?> cluster, int coordinator, String ks, String table)\n    {\n        QueryResult rs = queryParentRepairHistory(cluster, coordinator, ks, table);\n        validateExistingParentRepair(rs, row -> {\n            \r\n            Assert.assertNotNull(\"finished_at not found, the repair is not complete?\", row.getTimestamp(\"finished_at\"));\n\n            \r\n            Assert.assertNull(\"Exception found\", row.getString(\"exception_stacktrace\"));\n            Assert.assertNull(\"Exception found\", row.getString(\"exception_message\"));\n        });\n    }\n","realPath":"test/distributed/org/apache/cassandra/distributed/test/DistributedRepairUtils.java","repoName":"cassandra","snippetEndLine":0,"snippetStartLine":0,"startLine":114,"status":"B"},{"authorDate":"2020-03-12 03:06:42","commitOrder":1,"curCode":"    public static void assertParentRepairFailedWithMessageContains(AbstractCluster<?> cluster, int coordinator, String ks, String table, String message)\n    {\n        QueryResult rs = queryParentRepairHistory(cluster, coordinator, ks, table);\n        validateExistingParentRepair(rs, row -> {\n            \r\n            Assert.assertNotNull(\"finished_at not found, the repair is not complete?\", row.getTimestamp(\"finished_at\"));\n\n            \r\n            Assert.assertNotNull(\"Exception not found\", row.getString(\"exception_stacktrace\"));\n            String exceptionMessage = row.getString(\"exception_message\");\n            Assert.assertNotNull(\"Exception not found\", exceptionMessage);\n\n            Assert.assertTrue(\"Unable to locate message '\" + message + \"' in repair error message: \" + exceptionMessage, exceptionMessage.contains(message));\n        });\n    }\n","date":"2020-03-13 00:37:39","endLine":146,"groupId":"4324","id":2,"instanceNumber":2,"isCurCommit":0,"methodName":"assertParentRepairFailedWithMessageContains","params":"(AbstractCluster<?>cluster@intcoordinator@Stringks@Stringtable@Stringmessage)","path":"/mnt/clonedata/CloneManagementServer/ManagementServer/consistResult/result-cassandra-10-0.7/blobInfo/CC_OUT/blobs/7f/162e14654ec071beb43d3231c525143738bcc2.src","preCode":"    public static void assertParentRepairFailedWithMessageContains(AbstractCluster<?> cluster, int coordinator, String ks, String table, String message)\n    {\n        QueryResult rs = queryParentRepairHistory(cluster, coordinator, ks, table);\n        validateExistingParentRepair(rs, row -> {\n            \r\n            Assert.assertNotNull(\"finished_at not found, the repair is not complete?\", row.getTimestamp(\"finished_at\"));\n\n            \r\n            Assert.assertNotNull(\"Exception not found\", row.getString(\"exception_stacktrace\"));\n            String exceptionMessage = row.getString(\"exception_message\");\n            Assert.assertNotNull(\"Exception not found\", exceptionMessage);\n\n            Assert.assertTrue(\"Unable to locate message '\" + message + \"' in repair error message: \" + exceptionMessage, exceptionMessage.contains(message));\n        });\n    }\n","realPath":"test/distributed/org/apache/cassandra/distributed/test/DistributedRepairUtils.java","repoName":"cassandra","snippetEndLine":0,"snippetStartLine":0,"startLine":132,"status":"B"}],"commitId":"cd9fd9e83f507e2bab5075399d812e3fb4368920","commitMessage":"@@@Refactor repair coordinator to centralize stage change logic and improved the public facing errors\n\nPatch by David Capwell; reviewed by Blake Eggleston.  Zhao Yang.  Dinesh Joshi.  and Alex Petrov for CASSANDRA-15564","date":"2020-03-13 00:37:39","modifiedFileCount":"16","status":"B","submitter":"David Capwell"},{"authorTime":"2020-09-09 09:23:30","codes":[{"authorDate":"2020-09-09 09:23:30","commitOrder":2,"curCode":"    public static void assertParentRepairSuccess(ICluster<IInvokableInstance> cluster, int coordinator, String ks, String table, Consumer<Row> moreSuccessCriteria)\n    {\n        Assert.assertNotNull(\"Invalid null value for moreSuccessCriteria\", moreSuccessCriteria);\n        QueryResult rs = queryParentRepairHistory(cluster, coordinator, ks, table);\n        validateExistingParentRepair(rs, row -> {\n            \r\n            Assert.assertNotNull(\"finished_at not found, the repair is not complete?\", row.getTimestamp(\"finished_at\"));\n\n            \r\n            Assert.assertNull(\"Exception found\", row.getString(\"exception_stacktrace\"));\n            Assert.assertNull(\"Exception found\", row.getString(\"exception_message\"));\n\n            moreSuccessCriteria.accept(row);\n        });\n    }\n","date":"2020-10-10 04:47:44","endLine":134,"groupId":"10172","id":3,"instanceNumber":1,"isCurCommit":1,"methodName":"assertParentRepairSuccess","params":"(ICluster<IInvokableInstance>cluster@intcoordinator@Stringks@Stringtable@Consumer<Row>moreSuccessCriteria)","path":"/mnt/clonedata/CloneManagementServer/ManagementServer/consistResult/result-cassandra-10-0.7/blobInfo/CC_OUT/blobs/fc/e67b52d154d5e8714ba7b7b67009af77d08adc.src","preCode":"    public static void assertParentRepairSuccess(AbstractCluster<?> cluster, int coordinator, String ks, String table)\n    {\n        QueryResult rs = queryParentRepairHistory(cluster, coordinator, ks, table);\n        validateExistingParentRepair(rs, row -> {\n            \r\n            Assert.assertNotNull(\"finished_at not found, the repair is not complete?\", row.getTimestamp(\"finished_at\"));\n\n            \r\n            Assert.assertNull(\"Exception found\", row.getString(\"exception_stacktrace\"));\n            Assert.assertNull(\"Exception found\", row.getString(\"exception_message\"));\n        });\n    }\n","realPath":"test/distributed/org/apache/cassandra/distributed/test/DistributedRepairUtils.java","repoName":"cassandra","snippetEndLine":0,"snippetStartLine":0,"startLine":120,"status":"M"},{"authorDate":"2020-09-09 09:23:30","commitOrder":2,"curCode":"    public static void assertParentRepairFailedWithMessageContains(ICluster<IInvokableInstance> cluster, int coordinator, String ks, String table, String message)\n    {\n        QueryResult rs = queryParentRepairHistory(cluster, coordinator, ks, table);\n        validateExistingParentRepair(rs, row -> {\n            \r\n            Assert.assertNotNull(\"finished_at not found, the repair is not complete?\", row.getTimestamp(\"finished_at\"));\n\n            \r\n            Assert.assertNotNull(\"Exception not found\", row.getString(\"exception_stacktrace\"));\n            String exceptionMessage = row.getString(\"exception_message\");\n            Assert.assertNotNull(\"Exception not found\", exceptionMessage);\n\n            Assert.assertTrue(\"Unable to locate message '\" + message + \"' in repair error message: \" + exceptionMessage, exceptionMessage.contains(message));\n        });\n    }\n","date":"2020-10-10 04:47:44","endLine":155,"groupId":"10172","id":4,"instanceNumber":2,"isCurCommit":1,"methodName":"assertParentRepairFailedWithMessageContains","params":"(ICluster<IInvokableInstance>cluster@intcoordinator@Stringks@Stringtable@Stringmessage)","path":"/mnt/clonedata/CloneManagementServer/ManagementServer/consistResult/result-cassandra-10-0.7/blobInfo/CC_OUT/blobs/fc/e67b52d154d5e8714ba7b7b67009af77d08adc.src","preCode":"    public static void assertParentRepairFailedWithMessageContains(AbstractCluster<?> cluster, int coordinator, String ks, String table, String message)\n    {\n        QueryResult rs = queryParentRepairHistory(cluster, coordinator, ks, table);\n        validateExistingParentRepair(rs, row -> {\n            \r\n            Assert.assertNotNull(\"finished_at not found, the repair is not complete?\", row.getTimestamp(\"finished_at\"));\n\n            \r\n            Assert.assertNotNull(\"Exception not found\", row.getString(\"exception_stacktrace\"));\n            String exceptionMessage = row.getString(\"exception_message\");\n            Assert.assertNotNull(\"Exception not found\", exceptionMessage);\n\n            Assert.assertTrue(\"Unable to locate message '\" + message + \"' in repair error message: \" + exceptionMessage, exceptionMessage.contains(message));\n        });\n    }\n","realPath":"test/distributed/org/apache/cassandra/distributed/test/DistributedRepairUtils.java","repoName":"cassandra","snippetEndLine":0,"snippetStartLine":0,"startLine":141,"status":"M"}],"commitId":"1728da30e4e7858d30178ef74350af3e690adf0c","commitMessage":"@@@ Consolidate node liveness check for forced repair\n\n Patch by Yifan Cai; Reviewed by Blake Eggleston for CASSANDRA-16113\n","date":"2020-10-10 04:47:44","modifiedFileCount":"8","status":"M","submitter":"yifan-c"}]
